theme: jekyll-theme-cayman
title: Welcome to jonnymaserati's homepage!
description: The adventures of jonnymaserati in Wonderland.
avatar: https://avatars.githubusercontent.com/u/41046859?s=460&u=845b74e5ad4437fd1f6f2634b004b16bd0d2f48b&v=4
